# Generated by Django 5.0.2 on 2024-03-01 16:47

import django.db.models.deletion
import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cakes_level_cakes_lft_cakes_rght_cakes_tree_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cakes',
            new_name='Cake',
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.image_path.upload_cakes, verbose_name='Картинка')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cakes.cake', verbose_name='Торт')),
            ],
        ),
    ]
